<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>AdobeUserManagementApi</PackageId>
    <Version>1.0.3</Version>
    <Authors>Andrew Gaston</Authors>
    <Owners>University of South Alabama</Owners>
    <Company>University of South Alabama</Company>
    <Title>Adobe User Management Api</Title>
    <Description>C# Wrapper for Adobe User Management API (UMAPI)</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/southalabama/AdobeUserManagementApi</PackageProjectUrl>
    <Copyright>Copyright 2021</Copyright>
    <AssemblyVersion>1.0.3</AssemblyVersion>
    <FileVersion>1.0.3</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="RestSharp.Serializers.NewtonsoftJson" Version="114.0.0" />
  </ItemGroup>

</Project>
